#!/bin/bash

jazzy --readme README.md --github_url https://github.com/sealz/license-parser --author Clayton Lengel-Zigich --podspec LicenseParser.podspec --module LicenseParser --sdk iphonesimulator9.3
